### ISSUE TITLE
"Get accesstoken failed. Username or password error!"" using correct username & password?

### ISSUE THREAD

**Issue by QuiveryNut** [SynTexDZN/homebridge-syntex-tuya#4]
This better describes my issue, with the correct login information in the config I have the error 

`[SynTexTuya] [ERROR] Code Fehler: Authentication fault: Get accesstoken failed. Username or password error! ( [tuyawebapi.js] bei Zeile [261] )`

I am using the correct username and password, for both the TuyaSmart platform and the SmartLife platform, just to be sure. Country code is set as "01" and plat is the default. I'm not sure if I'm doing something wrong?

**Comment by SynTexDZN** [comment]
I'm trying to reproduce this error by creating a dummy account on the TuyaSmart App. Just to be sure your config is correct could you please send in your plugin configuration with 'X' replacing your username and password?

**Comment by SynTexDZN** [comment]
Don't know if it matters that a leading zero is required in the country code just try '1'

**Comment by SynTexDZN** [comment]
Everything now working as expected? @QuiveryNut

~ **SynTex**
