### ISSUE TITLE
make directory and give permissions failed

### ISSUE THREAD

**Issue by digiconnz** [SynTexDZN/homebridge-syntex-tuya#5]
I have followed your instructions around this. Can you give further detail about where the directory should be located for the storage etc.

**Comment by SynTexDZN** [comment]
The best solution I think is to place the directory somewhere at `/var/` because it's for changeable system files. To be sure everything is correct use an absolute path. Something like `/var/homebridge/SynTex/log`. I hope that helps you :)

**Comment by SynTexDZN** [comment]
Is all now working well?
