### ISSUE TITLE
Device type incorrect

### ISSUE THREAD

**Issue by tsfischer** [SynTexDZN/homebridge-syntex-tuya#6]
Hi I currently am testing this with a single device, a Gosund smart dimmer switch. Homekit shows this as an outlet, and therefore I don't get any dimmer functions. Is there a way to override this in the config, or some other way to make this work?

**Comment by SynTexDZN** [comment]
Hey, great to hear from you :D

There is currently no option to overrride the service type in the config.
But if you want to you could join my discord server that I can get it to work.

[![Discord](https://img.shields.io/discord/442095224953634828?color=728ED5&label=discord)](https://discord.gg/XUqghtw4DE)

We first have to determine which `service_type` is send back from the Tuya API and then I will implement it into a beta version update the upcoming days.

~ **SynTex**
